#server:
#  port: 8090



logging:
  level:
    org.springframework.security: DEBUG
    log4j.logger.org.hibernate.SQL: DEBUG
    com.techolution: DEBUG
    
spring:
  kafka:
    consumer:
      group-id: consumer1
      auto-offset-reset: earliest
      bootstrap-servers:
      - 52.170.92.62:9092

custom:
  serviceurl: http://52.170.92.62:8095/telemetry/insert/data

  