#server:
#  port: 8090



logging:
  level:
    org.springframework.security: DEBUG
    log4j.logger.org.hibernate.SQL: DEBUG
    com.techolution: DEBUG
    
spring:
  kafka:
    
    producer:
      bootstrap-servers:
      -   localhost:9092
      

custom:
 # mqttbroker: tcp://192.168.2.81:1883
  mqttbroker: tcp://broker.mqttdashboard.com:1883
 # mqtttopic: techo/smartoffice/1
  mqtttopic: kawshik 
  roomid: room2
  kafkatopic: smartoffice
  mqttclientid: clientroom1

  